### PR TITLE
only the lock owner can release lock

### PR DESCRIPTION
**Pull request by razertory**
As it is [commented](https://github.com/nateware/redis-objects/blob/master/lib/redis/lock.rb#L66) , we need to find a way to prevent others delete the lock. A simple and efficient way is,

when try to get lock, we use
```shell
# redis
>  SETNX key, my_lock_id
```
when we try to release lock,
- check the `my_lock_id` == lock_id, if it is
- release the lock

### CODE REVIEW

**Comment by nateware** [comment]
This is a good idea, but the usage of eval is not safe. Could this be rewritten as a lambda, or as a private method to call?

**Comment by razertory** [comment]
Is it means that the [RELEASE_LOCK_SCRIPT](https://github.com/nateware/redis-objects/pull/242/commits/c3b306b8d37e9f0eea0727444297693b0d296509#diff-eed187523a492b1272323d882ee14ca4R15) should be defined in private [release_lock](https://github.com/nateware/redis-objects/pull/242/commits/c3b306b8d37e9f0eea0727444297693b0d296509#diff-eed187523a492b1272323d882ee14ca4R94) method ?

**Comment by razertory** [comment]
Sure, but the release_lock method is private

**Comment by nateware** [comment]
This patch won’t work on distributed systems. It will work in a single
instance in the local unit test, but if you imagine multiple servers each
with their own instance of secureRandom, you’ll see that won’t work.

**Pull request closed without merging**
